//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhHoc
    {
        public ChuongTrinhHoc()
        {
            this.LopHocs = new HashSet<LopHoc>();
        }
    
        public string ctID { get; set; }
        public string ctTen { get; set; }
    
        public virtual ICollection<LopHoc> LopHocs { get; set; }
    }
}
