//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHocMo
    {
        public MonHocMo()
        {
            this.BuoiHocs = new HashSet<BuoiHoc>();
            this.LichThis = new HashSet<LichThi>();
            this.SinhVienMonHocs = new HashSet<SinhVienMonHoc>();
        }
    
        public string mhmID { get; set; }
        public string mhID { get; set; }
        public int sobuoi { get; set; }
        public Nullable<System.DateTime> ngayBatDau { get; set; }
        public string giohoc { get; set; }
        public string gvID { get; set; }
    
        public virtual ICollection<BuoiHoc> BuoiHocs { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual ICollection<LichThi> LichThis { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual ICollection<SinhVienMonHoc> SinhVienMonHocs { get; set; }
    }
}
