//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public MonHoc()
        {
            this.MonHocMoes = new HashSet<MonHocMo>();
        }
    
        public string mhID { get; set; }
        public string mhTen { get; set; }
    
        public virtual ICollection<MonHocMo> MonHocMoes { get; set; }
    }
}
