//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quanly
    {
        public string qlyID { get; set; }
        public string qlyMatKhau { get; set; }
        public Nullable<bool> qlyRole { get; set; }
        public Nullable<bool> qlyGioiTinh { get; set; }
        public string qlyTen { get; set; }
        public string qlyDiaChi { get; set; }
        public string qlyDienThoai { get; set; }
        public Nullable<System.DateTime> qlyNgaySinh { get; set; }
        public Nullable<System.DateTime> qlyThoiViec { get; set; }
    }
}
