//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public SinhVien()
        {
            this.SinhVienMonHocs = new HashSet<SinhVienMonHoc>();
        }
    
        public string svID { get; set; }
        public string svMatKhau { get; set; }
        public string svTen { get; set; }
        public bool svGioiTinh { get; set; }
        public System.DateTime svBirhday { get; set; }
        public string svDiaChi { get; set; }
        public string svDienThoai { get; set; }
        public string lopID { get; set; }
        public Nullable<System.DateTime> svNghiHoc { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual ICollection<SinhVienMonHoc> SinhVienMonHocs { get; set; }
    }
}
