//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVienMonHoc
    {
        public SinhVienMonHoc()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
        }
    
        public int svmhID { get; set; }
        public string mhmID { get; set; }
        public string svID { get; set; }
        public Nullable<double> diem1 { get; set; }
        public Nullable<double> diem2 { get; set; }
        public Nullable<double> diem3 { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> ketqua { get; set; }
    
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        public virtual MonHocMo MonHocMo { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
